# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK 11
      uses: actions/setup-java@v1.3.0
      with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
          java-version: 11
          # The package type (jre, jdk, jdk+fx)
          java-package: jdk
          # The architecture (x86, x64) of the package.
          architecture: x64
          # ID of the distributionManagement repository in the pom.xml file. Default is `github`
          #server-id: # optional
          # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
          #server-username: # optional
          # Environment variable name for password or token for authentication to the Apache Maven repository. Default is $GITHUB_TOKEN
          #server-password: # optional
    - name: Build with Maven
      run: mvn -B package --file pom.xml
